name: Trivy Security Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  trivy-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 🔥 IMPORTANTE: primero SOLO compilar sin tests
      - name: Compile Project
        run: mvn clean compile -DskipTests

      # 🔥 Trivy versión estable (NO uses la 0.36)
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          scanners: vuln
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          ignore-unfixed: true
          hide-progress: true
          exit-code: "0"

      - name: Finish
        run: echo "Pipeline OK"